name: compressx
description: Premium image & PDF utility app
publish_to: "none"

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Firebase core & auth
  firebase_core: ^4.4.0
  firebase_auth: ^6.1.4
  google_sign_in: ^7.2.0

  # Design & responsiveness
  flutter_screenutil: ^5.9.3
  google_fonts: ^6.2.1

  # State management / DI
  flutter_riverpod: ^2.5.1

  # Navigation
  go_router: ^14.2.0

  # File & media processing
  image_picker: ^1.1.2
  flutter_image_compress: ^2.3.0
  pdf: ^3.11.1
  printing: ^5.13.4

  # Storage / paths
  path_provider: ^2.1.4
  path: ^1.9.0

  # Sharing & permissions
  share_plus: ^10.0.2
  permission_handler: ^11.3.1

  # Connectivity
  connectivity_plus: ^6.1.0

  # Animations
  flutter_animate: ^4.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

